---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ammix-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: rpmfusion
      files:
        - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
      copr:
        - bieszczaders/kernel-cachyos-addons
        - ilyaz/LACT
    optfix:
      - vivaldi
    install:
      skip-unavailable: true
      packages:
        - neovim
        - zstd
        - lact
        - vivaldi-stable
        - vulkan-tools
        - libva-utils
        - firewall-config
        - steam-devices
        - usbutils
        - jq
        - gnome-shell-extension-gsconnect
        - nautilus-python
        - nautilus-gsconnect
        - podman-docker
        - podman
        - podman-compose
        - pcsc-tools
        - heif-pixbuf-loader
        - libheif
        - mpv
        - emacs
        - emacs-common
        - emacsclient
        - electrum
        - flatpak-spawn
        - alsa-firmware
        - ffmpegthumbnailer
        - distrobox
        - wireguard-tools
        - openssl
        - pam-u2f
        - pamu2fcfg
        - pam_yubico
        - yubikey-manager
        - yubico-piv-tool
        - fido2-tools
        - smartmontools
        - wl-clipboard
        - scx-scheds
        - stow
        - just
        - wcurl
        - gamemode
        - google-noto-fonts-all
        - liberation-fonts-all
        - fira-code-fonts
        - wqy-zenhei-fonts
        - nautilus-python
        - lm_sensors
        - libgtop2-devel
        - papers
        - showtime
        - xz-utils
        - VirtualBox
        - appimagelauncher
        - rpmfusion-nonfree-release-tainted
        - "*-firmware"
        - akmods
        - kernel-devel
        - kernel-headers
        - gcc
        - make
        - elfutils-libelf-devel
        - https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher-2.2.0-travis995.0f91801.x86_64.rpm
    group-install:
      skip-unavailable: true
      packages:
        - multimedia
        - virtualization
    remove:
      packages:
        - firefox
        - firefox-langpacks
    replace:
    - from-repo: rpmfusion
      allow-erasing: true
      packages:
        - old: ffmpeg-free
          new: ffmpeg
        - old: mesa-vulkan-drivers
          new: mesa-vulkan-drivers-freeworld
        - old: mesa-va-drivers
          new: mesa-va-drivers-freeworld

  - type: kargs
    kargs:
      - quiet
      - splash
      - udev.log_priority=3
      - vconsole.keymap=de-us
      - amdgpu.ppfeaturemask=0xfffd7fff

  - type: script
    snippets:
      - "plymouth-set-default-theme catppuccin-mocha"
    scripts:
      - akmods.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
      - scope: user
        install:
          - io.gitlab.librewolf-community
          - app.zen_browser.zen
          - com.discordapp.Discord
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - com.vysp3r.ProtonPlus
          - md.obsidian.Obsidian
          - com.valvesoftware.Steam
          - com.github.tchx84.Flatseal
          - io.bassi.Amberol
          - app.drey.EarTag
          - de.schmidhuberj.DieBahn
          - io.gitlab.adhami3310.Converter
          - io.github.idevecore.Valuta
          - com.github.ADBeveridge.Raider
          - info.febvre.Komikku
          - com.belmoussaoui.Decoder
          - dev.geopjr.Collision
          - org.gnome.gitlab.YaLTeR.Identity
          - com.github.finefindus.eyedropper
          - io.github.fizzyizzy05.binary
          - page.tesk.Refine
          - com.yubico.yubioath
          - com.bitwarden.desktop
          - com.tutanota.Tutanota
          - io.github.flattool.Warehouse


  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - NerdFontsSymbolsOnly
      google-fonts:
        - Inter
        - Victor Mono

  - type: gschema-overrides

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Fullscreen Avoider

  - type: systemd
    system:
      enabled:
        - scx_loader.service
        - libvirtd.service
        - lactd.service
        - ammix-bootc-update.timer
        - flatpak-update.timer
      disabled:
        - grub-boot-success.timer

  - type: os-release
    properties:
      ID: fedora
      NAME: Ammix
      PRETTY_NAME: Ammix Silverblue

  - type: initramfs

  - type: signing
