---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ammix-blue
# description will be included in the image's metadata
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      nonfree: rpmfusion
      copr:
        - bieszczaders/kernel-cachyos-addons
        - ilyaz/LACT
      files:
        - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    install:
      packages:
        - terra-release
        - terra-release-extras
        - rpmfusion-nonfree-release-tainted
    replace:
      - from-repo: fedora
        packages:
          - old: OpenCL-ICD-Loader
            new: ocl-icd
      - from-repo: terra-extras
        allow-erasing: true
        packages:
          - old: ffmpeg-free
            new: ffmpeg

  - type: script
    scripts:
      - repos.sh

  - type: dnf
    optfix:
      - vivaldi
      - Filen
    install:
      packages:
        - https://cdn.filen.io/@filen/desktop/release/latest/Filen_linux_x86_64.rpm
        - steam-devices
        - akmods
        - mpv
        - VirtualBox
        - btrfs-assistant
        - ghostty
        - kitty
        - vivaldi-stable
        - qutebrowser
        - vim
        - emacs-pgtk
        - emacsclient
        - "*-firmware"
        - zstd
        - lact
        - vulkan-tools
        - libva-utils
        - firewall-config
        - usbutils
        - usbmuxd
        - ifuse
        - gnome-shell-extension-gsconnect
        - nautilus-python
        - nautilus-gsconnect
        - podman-docker
        - podman
        - podman-compose
        - podman-machine
        - podman-tui
        - pcsc-tools
        - electrum
        - flatpak-spawn
        - ffmpegthumbnailer
        - distrobox
        - wireguard-tools
        - openssl
        - pam-u2f
        - pamu2fcfg
        - pam_yubico
        - yubikey-manager
        - yubico-piv-tool
        - fido2-tools
        - smartmontools
        - wl-clipboard
        - scx-scheds
        - stow
        - just
        - wcurl
        - heif-pixbuf-loader
        - libheif
        - ffmpeg-libs
        - ffmpegthumbnailer
        - gamemode
        - bibata-cursor-theme
        - google-noto-sans-fonts
        - google-noto-serif-fonts
        - google-noto-emoji-fonts
        - google-noto-sans-cjk-fonts
        - google-noto-serif-cjk-fonts
        - liberation-fonts
        - rsms-inter-fonts
        - fira-code-fonts
        - firacode-nerd-fonts
        - nerdfontssymbolsonly-nerd-fonts
        - wqy-zenhei-fonts
        - sysprof
        - lm_sensors
        - libgtop2-devel
        - wayland-devel
        - egl-wayland-devel
        - mesa-libgbm-devel
        - libglvnd-devel
        - libxkbcommon-devel
        - systemd-devel
        - dbus-devel
        - libdecor-devel
        - fontconfig-devel
        - freetype-devel
        - gtk4-devel
        - libadwaita-devel
        - pipewire-devel
        - xdg-desktop-portal-devel
        - xz
        - kernel-devel
        - kernel-headers
        - elfutils-libelf-devel
    group-install:
      skip-unavailable: true
      packages:
        - multimedia
        - virtualization
        - development-tools
        - development-libs
        - c-development
    remove:
      packages:
        - firefox
        - firefox-langpacks


  - type: kargs
    kargs:
      - quiet
      - splash
      - udev.log_priority=3
      - vconsole.keymap=de-us
      - amdgpu.ppfeaturemask=0xfffd7fff

  - type: script
    snippets:
      - "plymouth-set-default-theme catppuccin-mocha"
    scripts:
      - akmods.sh

  - type: default-flatpaks
    configurations:
      - scope: user
        notify: true
        install:
          - io.gitlab.librewolf-community
          - app.zen_browser.zen
          - com.discordapp.Discord
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - com.vysp3r.ProtonPlus
          - md.obsidian.Obsidian
          - com.valvesoftware.Steam
          - com.github.tchx84.Flatseal
          - io.bassi.Amberol
          - app.drey.EarTag
          - de.schmidhuberj.DieBahn
          - io.gitlab.adhami3310.Converter
          - io.github.idevecore.Valuta
          - com.github.ADBeveridge.Raider
          - info.febvre.Komikku
          - com.belmoussaoui.Decoder
          - dev.geopjr.Collision
          - org.gnome.gitlab.YaLTeR.Identity
          - com.github.finefindus.eyedropper
          - io.github.fizzyizzy05.binary
          - page.tesk.Refine
          - com.yubico.yubioath
          - com.bitwarden.desktop
          - com.tutanota.Tutanota
          - org.gnome.Papers
          - org.gnome.Showtime
          - app.drey.Warp
          - io.github.flattool.Warehouse

  - type: fonts
    fonts:
      google-fonts:
        - Victor Mono

  - type: gschema-overrides

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Fullscreen Avoider

  - type: systemd
    system:
      enabled:
        - scx_loader.service
        - libvirtd.service
        - lactd.service
        - ammix-bootc-update.timer
        - flatpak-update.timer
        - podman.socket
      masked:
        - grub-boot-success.timer
        - systemd-remount-fs.service
        - akmods-keygen@akmods-keygen.service
        - rpm-ostreed-automatic.service
        - rpm-ostreed-automatic.timer
    user:
      enabled:
        - ammix-emacs.service

  - type: os-release
    properties:
      ID: fedora
      NAME: Ammix
      PRETTY_NAME: Ammix Silverblue

  - type: initramfs

  - type: signing
