---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ammix-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: rpmfusion
      files:
        - https://repo.vivaldi.com/archive/vivaldi-fedora.repo
      copr:
        - bieszczaders/kernel-cachyos-addons
    optfix:
      - vivaldi
    install:
      skip-unavailable: true
      packages:
        - neovim
        - zstd
        - vivaldi-stable
        - steam-devices
        - usbutils
        - jq
        - podman-docker
        - podman
        - docker-compose
        - heif-pixbuf-loader
        - libheif
        - mpv
        - flatpak-spawn
        - alsa-firmware
        - ffmpegthumbnailer
        - distrobox
        - wireguard-tools
        - openssl
        - pam-u2f
        - pamu2fcfg
        - pam_yubico
        - yubikey-manager
        - yubico-piv-tool
        - fido2-tools
        - smartmontools
        - wl-clipboard
        - scx-scheds
        - stow
        - just
        - gamemode
        - gum
        - google-noto-fonts-all
        - liberation-fonts-all
        - wqy-zenhei-fonts
        - nautilus-python
        - papers
        - showtime
        - xz-utils
        - VirtualBox
        - emacs-pgtk
        - rpmfusion-nonfree-release-tainted
        - "*-firmware"
    group-install:
      skip-unavailable: true
      packages:
        - multimedia
        - virtualization
    remove:
      packages:
        - firefox
        - firefox-langpacks
    replace:
    - from-repo: rpmfusion
      allow-erasing: true
      packages:
        - old: ffmpeg-free
          new: ffmpeg
        - old: mesa-vulkan-drivers
          new: mesa-vulkan-drivers-freeworld
        - old: mesa-va-drivers
          new: mesa-va-drivers-freeworld

  - type: kargs
    kargs:
      - amdgpu.ppfeaturemask=0xfffd7fff

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
      - scope: user
        install:
          - io.gitlab.librewolf-community
          - app.zen_browser.zen
          - com.discordapp.Discord
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - com.usebottles.bottles
          - com.vysp3r.ProtonPlus
          - md.obsidian.Obsidian
          - com.valvesoftware.Steam
          - com.github.tchx84.Flatseal
          - org.musicbrainz.Picard
          - io.bassi.Amberol
          - io.github.ilya_zlobintsev.LACT
          - app.drey.EarTag
          - de.schmidhuberj.DieBahn
          - io.gitlab.adhami3310.Converter
          - io.github.idevecore.Valuta
          - com.github.ADBeveridge.Raider
          - info.febvre.Komikku
          - com.belmoussaoui.Decoder
          - dev.geopjr.Collision
          - org.gnome.gitlab.YaLTeR.Identity
          - com.github.finefindus.eyedropper
          - io.github.fizzyizzy05.binary
          - page.tesk.Refine

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Inter
        - Victor Mono

  - type: gnome-extensions
    install:
      - Blur my Shell
      - GSConnect
      - Fullscreen Avoider

  - type: systemd
    system:
      enabled:
        - scx_loader.service
        - rpm-ostreed-automatic.timer
        - libvirtd.service

  - type: initramfs

  - type: signing
